//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AperturasCajon
    {
        public int id { get; set; }
        public int idBaseCaja { get; set; }
        public System.DateTime fechaApertura { get; set; }
        public string obcerbacion { get; set; }
    
        public virtual BaseCaja BaseCaja { get; set; }
    }
}
