//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AutorizacionPC
    {
        public int id_autorizacion_pc { get; set; }
        public string serialnumber_pc { get; set; }
        public string Manufacturer_pc { get; set; }
        public string product_pc { get; set; }
        public string Version_pc { get; set; }
        public string nombre_equipo { get; set; }
        public Nullable<int> estado_equipo { get; set; }
    }
}
