//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class buyer_benefit
    {
        public int buyer_benefit_id { get; set; }
        public int cliente_id { get; set; }
        public int points { get; set; }
    
        public virtual Clientes Clientes { get; set; }
    }
}
