//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CargoDescuentoVentas
    {
        public int id { get; set; }
        public int idVenta { get; set; }
        public bool tipo { get; set; }
        public int codigo { get; set; }
        public string razon { get; set; }
        public decimal valor { get; set; }
        public decimal @base { get; set; }
    
        public virtual TablaVentas TablaVentas { get; set; }
    }
}
