//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clientes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Clientes()
        {
            this.buyer_benefit = new HashSet<buyer_benefit>();
            this.CorreosCliente = new HashSet<CorreosCliente>();
            this.CorreosCliente1 = new HashSet<CorreosCliente>();
            this.R_CompraCliente = new HashSet<R_CompraCliente>();
            this.R_CotizacionCliente = new HashSet<R_CotizacionCliente>();
            this.R_CotizacionCliente1 = new HashSet<R_CotizacionCliente>();
        }
    
        public int id { get; set; }
        public int typeDocumentIdentification_id { get; set; }
        public int typeOrganization_id { get; set; }
        public int municipality_id { get; set; }
        public int typeRegime_id { get; set; }
        public int typeLiability_id { get; set; }
        public int typeTaxDetail_id { get; set; }
        public string nameCliente { get; set; }
        public string tradeName { get; set; }
        public string phone { get; set; }
        public string adress { get; set; }
        public string email { get; set; }
        public string merchantRegistration { get; set; }
        public string identificationNumber { get; set; }
        public Nullable<int> idTipoTercero { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<buyer_benefit> buyer_benefit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CorreosCliente> CorreosCliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CorreosCliente> CorreosCliente1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<R_CompraCliente> R_CompraCliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<R_CotizacionCliente> R_CotizacionCliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<R_CotizacionCliente> R_CotizacionCliente1 { get; set; }
    }
}
