//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comanda
    {
        public int id { get; set; }
        public int idVenta { get; set; }
        public string nombreCuenta { get; set; }
        public string nombreProducto { get; set; }
        public string presentacion { get; set; }
        public Nullable<decimal> unidad { get; set; }
        public string observacion { get; set; }
        public string adiciones { get; set; }
        public string estado { get; set; }
        public string tipoComanda { get; set; }
    }
}
