//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComandaAdiciones
    {
        public int id { get; set; }
        public int idVenta { get; set; }
        public int idDetalleVenta { get; set; }
        public string producto { get; set; }
        public int idAdicion { get; set; }
        public string nombreAdicion { get; set; }
        public string estado { get; set; }
        public string tipoComanda { get; set; }
    }
}
