//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Compras
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Compras()
        {
            this.DocumentoSoporte = new HashSet<DocumentoSoporte>();
        }
    
        public int id { get; set; }
        public System.Guid guidCompra { get; set; }
        public System.DateTime fechaCompra { get; set; }
        public string tipoFacturaCompra { get; set; }
        public string prefijoFacturaCompra { get; set; }
        public string numeroFactura { get; set; }
        public Nullable<int> number { get; set; }
        public string notes { get; set; }
        public int payment_form_id { get; set; }
        public string namePayment_form { get; set; }
        public int payment_method_id { get; set; }
        public string namePayment_method { get; set; }
        public System.DateTime patment_due_date { get; set; }
        public int estadoCompra { get; set; }
        public Nullable<int> idc { get; set; }
        public Nullable<int> idResolucion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocumentoSoporte> DocumentoSoporte { get; set; }
    }
}
