//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConsecutivoVentaUsado
    {
        public int id { get; set; }
        public int numeroConsecutivoVenta { get; set; }
        public int idUsuarioVenta { get; set; }
        public int numeroCajaActivaVenta { get; set; }
        public Nullable<int> estadoConsecutivoVenta { get; set; }
    }
}
