//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cotizaciones
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cotizaciones()
        {
            this.DetalleCotizacion = new HashSet<DetalleCotizacion>();
            this.R_CotizacionCliente = new HashSet<R_CotizacionCliente>();
        }
    
        public int id { get; set; }
        public System.DateTime fechaCotizacion { get; set; }
        public int numeroCotizacion { get; set; }
        public decimal ivaCotizacion { get; set; }
        public string fechaVencimiento { get; set; }
        public string observacionVenta { get; set; }
        public int IdSede { get; set; }
        public System.Guid guidCotizacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleCotizacion> DetalleCotizacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<R_CotizacionCliente> R_CotizacionCliente { get; set; }
    }
}
