//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CuentasServicio
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CuentasServicio()
        {
            this.R_CuentaServicio_DetalleServicio = new HashSet<R_CuentaServicio_DetalleServicio>();
        }
    
        public int id { get; set; }
        public int idServicio { get; set; }
        public string nombreCuentaServicio { get; set; }
        public Nullable<int> estadoCuenta { get; set; }
        public Nullable<int> estadoPreCuenta { get; set; }
    
        public virtual ServicioMesa ServicioMesa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<R_CuentaServicio_DetalleServicio> R_CuentaServicio_DetalleServicio { get; set; }
    }
}
