//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CuentasVendedor
    {
        public int id { get; set; }
        public System.DateTime fechaVenta { get; set; }
        public int numeroVenta { get; set; }
        public int idVendedor { get; set; }
        public int idMesa { get; set; }
        public string nombreMesa { get; set; }
        public decimal total { get; set; }
    }
}
