//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DestapeProducto
    {
        public int id { get; set; }
        public int idUsuarioDestape { get; set; }
        public int idProductoDestapar { get; set; }
        public int cantidadDestapar { get; set; }
        public int idProductoSurtir { get; set; }
        public int cantidadSurtir { get; set; }
        public System.DateTime fechaDestapeProducto { get; set; }
        public System.TimeSpan horaDestapeProducto { get; set; }
    }
}
