//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleVentaActiva
    {
        public int id { get; set; }
        public Nullable<int> idCajero { get; set; }
        public Nullable<int> numeroVenta { get; set; }
        public Nullable<int> idProducto { get; set; }
        public string descripcionEditada { get; set; }
        public Nullable<int> costoDetalleVentaActiva { get; set; }
        public Nullable<int> cantidadDetalleVentaActiva { get; set; }
        public Nullable<int> totalDetalleVentaActiva { get; set; }
    }
}
