//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleOrdenFabrica
    {
        public int id { get; set; }
        public int idOrdenDetalle { get; set; }
        public int idInsumoOrden { get; set; }
        public string descripcionInsumoOrden { get; set; }
        public Nullable<decimal> cantidadInsumoOrden { get; set; }
        public decimal costoInsumoUnidad { get; set; }
        public decimal costoTotalInsumoOrden { get; set; }
    }
}
