//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleCotizacion
    {
        public int id { get; set; }
        public int idCotizacion { get; set; }
        public string nombreProducto { get; set; }
        public decimal precioVenta { get; set; }
        public int estadoDetalle { get; set; }
        public decimal ivaDetalle { get; set; }
        public decimal cantidadDetalle { get; set; }
        public string codigoProducto { get; set; }
        public string observacion { get; set; }
        public Nullable<int> idPresentacion { get; set; }
    
        public virtual Cotizaciones Cotizaciones { get; set; }
    }
}
