//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleVenta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DetalleVenta()
        {
            this.AdicionDetalleText = new HashSet<AdicionDetalleText>();
            this.AdicionDetalleVenta = new HashSet<AdicionDetalleVenta>();
            this.CargosDescuentosDetalleVenta = new HashSet<CargosDescuentosDetalleVenta>();
            this.ComandImpresaa = new HashSet<ComandImpresaa>();
            this.DetalleInsumo = new HashSet<DetalleInsumo>();
            this.R_CuentaCliente_DetalleVenta = new HashSet<R_CuentaCliente_DetalleVenta>();
        }
    
        public int id { get; set; }
        public int idVenta { get; set; }
        public int idPresentacion { get; set; }
        public string nombreProducto { get; set; }
        public decimal costoUnidad { get; set; }
        public decimal precioVenta { get; set; }
        public int estadoDetalle { get; set; }
        public Nullable<decimal> ivaDetalle { get; set; }
        public decimal cantidadDetalle { get; set; }
        public string codigoProducto { get; set; }
        public string observacion { get; set; }
        public Nullable<System.Guid> guidDetalle { get; set; }
        public string opciones { get; set; }
        public string adiciones { get; set; }
        public Nullable<int> impuesto_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AdicionDetalleText> AdicionDetalleText { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AdicionDetalleVenta> AdicionDetalleVenta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CargosDescuentosDetalleVenta> CargosDescuentosDetalleVenta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ComandImpresaa> ComandImpresaa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleInsumo> DetalleInsumo { get; set; }
        public virtual Presentacion Presentacion { get; set; }
        public virtual Presentacion Presentacion1 { get; set; }
        public virtual TablaVentas TablaVentas { get; set; }
        public virtual TablaVentas TablaVentas1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<R_CuentaCliente_DetalleVenta> R_CuentaCliente_DetalleVenta { get; set; }
    }
}
