//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleServicio
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DetalleServicio()
        {
            this.DetalleComanda = new HashSet<DetalleComanda>();
            this.DetalleComanda1 = new HashSet<DetalleComanda>();
            this.DetalleComanda2 = new HashSet<DetalleComanda>();
        }
    
        public int id { get; set; }
        public int idServicio { get; set; }
        public int idPresentacion { get; set; }
        public string nombreProducto { get; set; }
        public decimal costoUnidad { get; set; }
        public decimal precioVenta { get; set; }
        public int estadoDetalle { get; set; }
        public Nullable<decimal> ivaDetalle { get; set; }
        public decimal cantidadDetalle { get; set; }
        public string codigoProducto { get; set; }
        public string observacion { get; set; }
        public Nullable<System.Guid> guidDetalle { get; set; }
        public string opciones { get; set; }
        public string adiciones { get; set; }
        public Nullable<int> impuesto_id { get; set; }
        public Nullable<int> estadoComanda { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleComanda> DetalleComanda { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleComanda> DetalleComanda1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleComanda> DetalleComanda2 { get; set; }
        public virtual ServicioMesa ServicioMesa { get; set; }
        public virtual ServicioMesa ServicioMesa1 { get; set; }
        public virtual ServicioMesa ServicioMesa2 { get; set; }
    }
}
