//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleCompra
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DetalleCompra()
        {
            this.InsumosDetalleCompra = new HashSet<InsumosDetalleCompra>();
        }
    
        public int id { get; set; }
        public int idCompra { get; set; }
        public int idProducto { get; set; }
        public string nombreProducto { get; set; }
        public Nullable<decimal> cantidad { get; set; }
        public Nullable<decimal> precioUnitario { get; set; }
        public int estadoDetalle { get; set; }
        public int idPresentacion { get; set; }
        public decimal contenidoPresentacion { get; set; }
        public Nullable<System.Guid> guiDetalleCompra { get; set; }
    
        public virtual Presentacion Presentacion { get; set; }
        public virtual Producto Producto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InsumosDetalleCompra> InsumosDetalleCompra { get; set; }
    }
}
