//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentoSoporte
    {
        public int idDocumentoSoporte { get; set; }
        public int idCompra { get; set; }
        public string numbrer { get; set; }
        public string uuid { get; set; }
        public string issue_date { get; set; }
        public string dataQR { get; set; }
        public string imagenQR { get; set; }
        public string archivoJSON { get; set; }
    
        public virtual Compras Compras { get; set; }
    }
}
