//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Domicilios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Domicilios()
        {
            this.R_VentaDomicilio = new HashSet<R_VentaDomicilio>();
            this.SeguimientoDomicilio = new HashSet<SeguimientoDomicilio>();
        }
    
        public System.Guid id { get; set; }
        public System.DateTime fecha { get; set; }
        public int idVenta { get; set; }
        public int idEstado { get; set; }
        public System.Guid idCliente { get; set; }
    
        public virtual ClienteDomicilio ClienteDomicilio { get; set; }
        public virtual EstadoDomicilio EstadoDomicilio { get; set; }
        public virtual TablaVentas TablaVentas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<R_VentaDomicilio> R_VentaDomicilio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SeguimientoDomicilio> SeguimientoDomicilio { get; set; }
    }
}
