//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class FacturaElectronicaJSON
    {
        public int id { get; set; }
        public int idventa { get; set; }
        public bool is_valid { get; set; }
        public Nullable<bool> is_restored { get; set; }
        public string algorithm { get; set; }
        public string zip_key { get; set; }
        public string status_code { get; set; }
        public string status_description { get; set; }
        public string status_message { get; set; }
        public string mail_sending_message { get; set; }
        public string errors_messages { get; set; }
        public string xml_name { get; set; }
        public string zip_name { get; set; }
        public string signature { get; set; }
        public string qr_code { get; set; }
        public string qr_link { get; set; }
        public string pdf_download_link { get; set; }
        public string xml_base64_bytes { get; set; }
        public string application_response_base64_bytes { get; set; }
        public string attached_document_base64_bytes { get; set; }
        public string pdf_base64_bytes { get; set; }
        public string zip_base64_bytes { get; set; }
        public Nullable<int> type_environment_id { get; set; }
    
        public virtual TablaVentas TablaVentas { get; set; }
        public virtual TablaVentas TablaVentas1 { get; set; }
    }
}
