//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gastos
    {
        public int id { get; set; }
        public System.DateTime fecha { get; set; }
        public string concepto { get; set; }
        public decimal valor { get; set; }
        public int idBolsillo { get; set; }
        public int idBasecaja { get; set; }
        public int idTipoGasto { get; set; }
        public Nullable<int> idSede { get; set; }
    
        public virtual BaseCaja BaseCaja { get; set; }
        public virtual Bolsillo Bolsillo { get; set; }
        public virtual TipoGasto TipoGasto { get; set; }
    }
}
