//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Impresora
    {
        public int id_impresora { get; set; }
        public string nombre_impresora { get; set; }
        public string nombrePunto { get; set; }
        public Nullable<int> codigo { get; set; }
        public Nullable<int> copias { get; set; }
        public Nullable<bool> estado { get; set; }
    }
}
