//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Impuestos
    {
        public int id { get; set; }
        public System.Guid guidImpuesto { get; set; }
        public int idProducto { get; set; }
        public int idImpuesto { get; set; }
        public string nombreImpuesto { get; set; }
        public decimal tax_amount { get; set; }
        public decimal taxable_amount { get; set; }
        public decimal porcentage { get; set; }
        public int impuestoCompra { get; set; }
        public int impuestoVenta { get; set; }
    
        public virtual Producto Producto { get; set; }
        public virtual Producto Producto1 { get; set; }
    }
}
