//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class InformacionEmpresa
    {
        public System.Guid id { get; set; }
        public string razonSocial { get; set; }
        public string nombreComercial { get; set; }
        public string nit { get; set; }
        public int idTipoContibuyente { get; set; }
        public int idRegimen { get; set; }
        public string direccion { get; set; }
        public string telefono { get; set; }
        public string correo { get; set; }
    
        public virtual TipoRegimen TipoRegimen { get; set; }
    }
}
