//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class InsumosDetalleCompra
    {
        public int id { get; set; }
        public int idDetalleCompra { get; set; }
        public int idProducto { get; set; }
        public string nombreProducto { get; set; }
        public decimal cantidad { get; set; }
        public int idPresentacion { get; set; }
        public int contenidoPresentacion { get; set; }
    
        public virtual DetalleCompra DetalleCompra { get; set; }
        public virtual DetalleCompra DetalleCompra1 { get; set; }
        public virtual Presentacion Presentacion { get; set; }
        public virtual Presentacion Presentacion1 { get; set; }
        public virtual Producto Producto { get; set; }
        public virtual Producto Producto1 { get; set; }
    }
}
