//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventarioTotal
    {
        public int id { get; set; }
        public int idSede { get; set; }
        public int idProducto { get; set; }
        public Nullable<decimal> costoUnidad { get; set; }
        public Nullable<decimal> porcentajeIVA { get; set; }
        public Nullable<decimal> stockInvetario { get; set; }
        public Nullable<decimal> inventarioInical { get; set; }
        public Nullable<decimal> porcentajeDescuento { get; set; }
    }
}
