//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kardex
    {
        public int id { get; set; }
        public string codigoProducto { get; set; }
        public string nombreProducto { get; set; }
        public decimal inventarioInicial { get; set; }
        public int idCategoria { get; set; }
        public Nullable<decimal> ajustes { get; set; }
        public Nullable<decimal> compras { get; set; }
        public Nullable<decimal> insumoCompras { get; set; }
        public Nullable<decimal> merma { get; set; }
        public Nullable<decimal> ventas { get; set; }
        public Nullable<decimal> ventasInsumos { get; set; }
        public Nullable<decimal> inventarioActual { get; set; }
    }
}
