//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MediosDePagoInternos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MediosDePagoInternos()
        {
            this.PagosVenta = new HashSet<PagosVenta>();
            this.R_MediosDePago_MediosDePagoInternos = new HashSet<R_MediosDePago_MediosDePagoInternos>();
        }
    
        public int id { get; set; }
        public string nombreMPI { get; set; }
        public Nullable<int> estado { get; set; }
        public int reporteDIAN { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PagosVenta> PagosVenta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<R_MediosDePago_MediosDePagoInternos> R_MediosDePago_MediosDePagoInternos { get; set; }
    }
}
