//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mesas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Mesas()
        {
            this.R_MesaMesero = new HashSet<R_MesaMesero>();
            this.R_ServicioMesa = new HashSet<R_ServicioMesa>();
            this.R_ServicioMesa1 = new HashSet<R_ServicioMesa>();
            this.R_ServicioMesa2 = new HashSet<R_ServicioMesa>();
            this.R_VentaMesa = new HashSet<R_VentaMesa>();
        }
    
        public int id { get; set; }
        public string nombreMesa { get; set; }
        public int estadoMesa { get; set; }
        public int idZona { get; set; }
        public Nullable<System.Guid> guidMesa { get; set; }
        public Nullable<int> widthMesa { get; set; }
    
        public virtual Zonas Zonas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<R_MesaMesero> R_MesaMesero { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<R_ServicioMesa> R_ServicioMesa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<R_ServicioMesa> R_ServicioMesa1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<R_ServicioMesa> R_ServicioMesa2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<R_VentaMesa> R_VentaMesa { get; set; }
    }
}
