//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotasCredito
    {
        public int id { get; set; }
        public int idVenta { get; set; }
        public string cufe { get; set; }
        public string numeroFactura { get; set; }
        public string fechaEmision { get; set; }
        public string fecahVensimiento { get; set; }
        public string dataQR { get; set; }
        public string imagenQR { get; set; }
    
        public virtual TablaVentas TablaVentas { get; set; }
    }
}
