//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notas_CreditoDebito
    {
        public System.Guid id { get; set; }
        public string tipoNota { get; set; }
        public System.DateTime fechaNota { get; set; }
        public int idVenta { get; set; }
        public int correctionConsept_id { get; set; }
        public string nameCorrectionConsept { get; set; }
        public string estadoNotaCredito { get; set; }
        public string descriptionNota { get; set; }
        public decimal descuentoVenta { get; set; }
        public decimal ivaVenta { get; set; }
        public decimal efectivoVenta { get; set; }
        public decimal cambioVenta { get; set; }
        public string tipoVenta { get; set; }
        public string estadoVenta { get; set; }
        public string tipoPago { get; set; }
        public string numeroReferenciaPago { get; set; }
        public Nullable<int> diasCredito { get; set; }
        public string fechaVencimiento { get; set; }
        public string observacionVenta { get; set; }
        public int IdSede { get; set; }
        public System.Guid guidVenta { get; set; }
        public decimal abonoTarjeta { get; set; }
        public Nullable<decimal> propina { get; set; }
        public decimal abonoEfectivo { get; set; }
        public Nullable<int> idMedioDePago { get; set; }
    
        public virtual TablaVentas TablaVentas { get; set; }
    }
}
