//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdenFabrica
    {
        public int id { get; set; }
        public int numeroOrdenFabrica { get; set; }
        public System.DateTime fechaInicioOrden { get; set; }
        public System.DateTime fechaEntregaIrden { get; set; }
        public int diasOrden { get; set; }
        public string nombreResponsableOrden { get; set; }
        public string descripcionProductoOrden { get; set; }
        public Nullable<decimal> costoOrdenInsumo { get; set; }
        public Nullable<decimal> costoOrdenManoObra { get; set; }
        public Nullable<decimal> totalConstoOren { get; set; }
        public Nullable<decimal> ValorFinalOrden { get; set; }
        public Nullable<decimal> Producido { get; set; }
        public string clienteOrden { get; set; }
        public string estadoOrdenFabricacion { get; set; }
        public string responsableOrden { get; set; }
    }
}
