//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdenServicio
    {
        public int id { get; set; }
        public System.DateTime fechaIngreso { get; set; }
        public System.DateTime fechaRetiro { get; set; }
        public int idTipoServicio { get; set; }
        public int idArticulo { get; set; }
        public string descriopcionOtro { get; set; }
        public string modeloArticulo { get; set; }
        public string serialArticulo { get; set; }
        public string accesoriosArticulo { get; set; }
        public string observacionIngreso { get; set; }
        public string descripcionServicio { get; set; }
        public string estadoOrdenServicio { get; set; }
        public Nullable<int> idCleinte { get; set; }
        public Nullable<int> numeroOrdenServicio { get; set; }
        public string usuarioRetiro { get; set; }
        public string usuarioIngreso { get; set; }
    }
}
