//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PagosVenta
    {
        public int id { get; set; }
        public int idVenta { get; set; }
        public int idMedioDePagointerno { get; set; }
        public decimal valorPago { get; set; }
        public Nullable<int> payment_methods_id { get; set; }
    
        public virtual MediosDePagoInternos MediosDePagoInternos { get; set; }
        public virtual TablaVentas TablaVentas { get; set; }
    }
}
