//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pedidos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pedidos()
        {
            this.ConsecutivoPedido1 = new HashSet<ConsecutivoPedido>();
            this.DetallePedido = new HashSet<DetallePedido>();
            this.R_PedidoVenta = new HashSet<R_PedidoVenta>();
        }
    
        public int id { get; set; }
        public int idEstadoPedido { get; set; }
        public System.Guid guidPedido { get; set; }
        public int idVendedor { get; set; }
        public int idCliente { get; set; }
        public System.DateTime fechaPedido { get; set; }
        public int diasEntrega { get; set; }
        public System.DateTime fechaEntrega { get; set; }
        public int consecutivoPedido { get; set; }
        public string observacionPedido { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConsecutivoPedido> ConsecutivoPedido1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetallePedido> DetallePedido { get; set; }
        public virtual EstadoPedido EstadoPedido { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<R_PedidoVenta> R_PedidoVenta { get; set; }
    }
}
