//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Presentacion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Presentacion()
        {
            this.DetalleCompra = new HashSet<DetalleCompra>();
            this.DetalleVenta = new HashSet<DetalleVenta>();
            this.DetalleVenta1 = new HashSet<DetalleVenta>();
            this.InsumosDetalleCompra = new HashSet<InsumosDetalleCompra>();
            this.Precios = new HashSet<Precios>();
        }
    
        public int id { get; set; }
        public int idTipoPresentacion { get; set; }
        public int idProducto { get; set; }
        public decimal contenidoPresentacion { get; set; }
        public int estadoPresentacion { get; set; }
        public decimal precioVenta { get; set; }
        public Nullable<decimal> porcentajeUtilidad { get; set; }
        public Nullable<decimal> valorUtilidad { get; set; }
        public Nullable<decimal> precioNeto { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleCompra> DetalleCompra { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleVenta> DetalleVenta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleVenta> DetalleVenta1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InsumosDetalleCompra> InsumosDetalleCompra { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Precios> Precios { get; set; }
        public virtual TipoPresentacion TipoPresentacion { get; set; }
    }
}
