//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto
    {
        public int id { get; set; }
        public System.Guid guidProducto { get; set; }
        public string codigoProducto { get; set; }
        public string nombreProducto { get; set; }
        public string descripcionProducto { get; set; }
        public int idCategoria { get; set; }
        public int idTipoMedida { get; set; }
        public int estadoProducto { get; set; }
        public int gramera { get; set; }
        public decimal costo_mas_impuesto { get; set; }
        public decimal inventarioInicial { get; set; }
        public int insumo { get; set; }
        public decimal inventarioMinimo { get; set; }
        public decimal costo_neto { get; set; }
        public decimal porcentaje_impuesto { get; set; }
        public int impuesto_id { get; set; }
    
        public virtual Categoria Categoria { get; set; }
        public virtual TipoMedida TipoMedida { get; set; }
    }
}
