//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class pViejos
    {
        public int id { get; set; }
        public string codigo { get; set; }
        public string nombreProducto { get; set; }
        public string descripcionProducto { get; set; }
        public string categoria { get; set; }
        public decimal costo { get; set; }
        public decimal precio { get; set; }
        public Nullable<decimal> impuesto { get; set; }
    }
}
