//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class R_ClienteVendedor
    {
        public int id { get; set; }
        public int idCliente { get; set; }
        public int idVendedor { get; set; }
        public int idSemana { get; set; }
    
        public virtual Semana Semana { get; set; }
    }
}
