//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class R_CotizacionCliente
    {
        public int id { get; set; }
        public int idCotizacion { get; set; }
        public int idCliente { get; set; }
        public Nullable<int> idSede { get; set; }
    
        public virtual Clientes Clientes { get; set; }
        public virtual Cotizaciones Cotizaciones { get; set; }
    }
}
