//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class R_CuentaServicio_DetalleServicio
    {
        public int id { get; set; }
        public int idDetalleServicio { get; set; }
        public int idCuentasServicio { get; set; }
    
        public virtual CuentasServicio CuentasServicio { get; set; }
        public virtual DetalleServicio DetalleServicio { get; set; }
    }
}
