//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class R_MesaMesero
    {
        public int id { get; set; }
        public int idMesa { get; set; }
        public int idMesero { get; set; }
    
        public virtual Mesas Mesas { get; set; }
        public virtual Vendedor Vendedor { get; set; }
    }
}
