//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class R_ProductoInsumo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public R_ProductoInsumo()
        {
            this.DetalleInsumo = new HashSet<DetalleInsumo>();
        }
    
        public int id { get; set; }
        public int idProducto { get; set; }
        public int idInsumo { get; set; }
        public int idUnidadMedida { get; set; }
        public decimal cantidadInsumo { get; set; }
        public int opcional { get; set; }
        public decimal precioInsumo { get; set; }
        public int estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleInsumo> DetalleInsumo { get; set; }
        public virtual Producto Producto { get; set; }
        public virtual Producto Producto1 { get; set; }
        public virtual Producto Producto2 { get; set; }
        public virtual Producto Producto3 { get; set; }
        public virtual Producto Producto4 { get; set; }
        public virtual Producto Producto5 { get; set; }
        public virtual Producto Producto6 { get; set; }
        public virtual Producto Producto7 { get; set; }
        public virtual TipoMedida TipoMedida { get; set; }
        public virtual TipoMedida TipoMedida1 { get; set; }
        public virtual TipoMedida TipoMedida2 { get; set; }
        public virtual TipoMedida TipoMedida3 { get; set; }
    }
}
