//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class R_ProductoInsumo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public R_ProductoInsumo()
        {
            this.DetalleInsumo = new HashSet<DetalleInsumo>();
        }
    
        public int id { get; set; }
        public int idProducto { get; set; }
        public int idInsumo { get; set; }
        public int idUnidadMedida { get; set; }
        public decimal cantidadInsumo { get; set; }
        public int opcional { get; set; }
        public Nullable<decimal> precioInsumo { get; set; }
        public Nullable<int> estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleInsumo> DetalleInsumo { get; set; }
        public virtual TipoMedida TipoMedida { get; set; }
    }
}
