//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class R_VentaUsuario
    {
        public int id { get; set; }
        public int idVenta { get; set; }
        public int idUsuario { get; set; }
        public Nullable<int> estado { get; set; }
    }
}
