//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReporteActualizacionEquipo
    {
        public int id_reposte_actualizacion_equipo { get; set; }
        public Nullable<System.DateTime> fecha_actualizacion_equipo { get; set; }
        public Nullable<System.TimeSpan> hora_actualizacion_equipo { get; set; }
        public string nombre_equipo_actualizado { get; set; }
        public string nombre_version_actualizado { get; set; }
    }
}
