//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RutaActualizacionEquipo
    {
        public int id_ruta_equipo_local { get; set; }
        public string nombre_equipo_local { get; set; }
        public string ruta_aplicaion_actualizacion { get; set; }
        public string ruta_carpeta_actualizacion { get; set; }
        public string ruta_facturas { get; set; }
        public string rutaImagen { get; set; }
        public string rutaArchivos { get; set; }
        public string rutaTutoriales { get; set; }
    }
}
