//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServicioMesa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ServicioMesa()
        {
            this.CuentasServicio = new HashSet<CuentasServicio>();
            this.DetalleServicio = new HashSet<DetalleServicio>();
            this.R_ServicioMesa = new HashSet<R_ServicioMesa>();
        }
    
        public int id { get; set; }
        public string nombreMesero { get; set; }
        public System.DateTime fecha { get; set; }
        public string aliasServicio { get; set; }
        public Nullable<int> estadoServicio { get; set; }
        public int idMesero { get; set; }
        public Nullable<decimal> porcentajePropina { get; set; }
        public Nullable<decimal> valorPropina { get; set; }
        public Nullable<int> estadoPreCuenta { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CuentasServicio> CuentasServicio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleServicio> DetalleServicio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<R_ServicioMesa> R_ServicioMesa { get; set; }
    }
}
