//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SoftwareDIAN
    {
        public System.Guid guidsoftwareDIAN { get; set; }
        public System.Guid idEmpresa { get; set; }
        public string idSoftware { get; set; }
        public string pinsoftware { get; set; }
    
        public virtual Empresas Empresas { get; set; }
    }
}
