//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TablaVentas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TablaVentas()
        {
            this.CargoDescuentoVentas = new HashSet<CargoDescuentoVentas>();
            this.DetalleVenta = new HashSet<DetalleVenta>();
            this.DetalleVenta1 = new HashSet<DetalleVenta>();
            this.Domicilios = new HashSet<Domicilios>();
            this.FacturaElectronica = new HashSet<FacturaElectronica>();
            this.FacturaElectronicaJSON = new HashSet<FacturaElectronicaJSON>();
            this.FacturaElectronicaJSON1 = new HashSet<FacturaElectronicaJSON>();
            this.ImprimirCuenta = new HashSet<ImprimirCuenta>();
            this.ImprimirFactura = new HashSet<ImprimirFactura>();
            this.Notas_CreditoDebito = new HashSet<Notas_CreditoDebito>();
            this.NotasCredito = new HashSet<NotasCredito>();
            this.PagosVenta = new HashSet<PagosVenta>();
            this.R_PedidoVenta = new HashSet<R_PedidoVenta>();
            this.R_VehiculoVenta = new HashSet<R_VehiculoVenta>();
            this.R_VehiculoVenta1 = new HashSet<R_VehiculoVenta>();
            this.R_VehiculoVenta2 = new HashSet<R_VehiculoVenta>();
            this.R_VentaBase = new HashSet<R_VentaBase>();
            this.R_VentaDomicilio = new HashSet<R_VentaDomicilio>();
            this.R_VentaMesa = new HashSet<R_VentaMesa>();
            this.R_VentaVendedor = new HashSet<R_VentaVendedor>();
            this.ReporteImpuestos = new HashSet<ReporteImpuestos>();
        }
    
        public int id { get; set; }
        public System.DateTime fechaVenta { get; set; }
        public int numeroVenta { get; set; }
        public decimal descuentoVenta { get; set; }
        public decimal efectivoVenta { get; set; }
        public decimal cambioVenta { get; set; }
        public string estadoVenta { get; set; }
        public string numeroReferenciaPago { get; set; }
        public Nullable<int> diasCredito { get; set; }
        public string observacionVenta { get; set; }
        public int IdSede { get; set; }
        public System.Guid guidVenta { get; set; }
        public decimal abonoTarjeta { get; set; }
        public Nullable<decimal> propina { get; set; }
        public decimal abonoEfectivo { get; set; }
        public Nullable<int> idMedioDePago { get; set; }
        public Nullable<int> idResolucion { get; set; }
        public Nullable<int> idFormaDePago { get; set; }
        public string razonDescuento { get; set; }
        public Nullable<int> idBaseCaja { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CargoDescuentoVentas> CargoDescuentoVentas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleVenta> DetalleVenta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleVenta> DetalleVenta1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Domicilios> Domicilios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FacturaElectronica> FacturaElectronica { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FacturaElectronicaJSON> FacturaElectronicaJSON { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FacturaElectronicaJSON> FacturaElectronicaJSON1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ImprimirCuenta> ImprimirCuenta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ImprimirFactura> ImprimirFactura { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Notas_CreditoDebito> Notas_CreditoDebito { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NotasCredito> NotasCredito { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PagosVenta> PagosVenta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<R_PedidoVenta> R_PedidoVenta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<R_VehiculoVenta> R_VehiculoVenta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<R_VehiculoVenta> R_VehiculoVenta1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<R_VehiculoVenta> R_VehiculoVenta2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<R_VentaBase> R_VentaBase { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<R_VentaDomicilio> R_VentaDomicilio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<R_VentaMesa> R_VentaMesa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<R_VentaVendedor> R_VentaVendedor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReporteImpuestos> ReporteImpuestos { get; set; }
    }
}
