//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TablaCompras
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TablaCompras()
        {
            this.CargoDescuentoCompra = new HashSet<CargoDescuentoCompra>();
            this.ConsecutivoCompras = new HashSet<ConsecutivoCompras>();
            this.ConsecutivoCompras1 = new HashSet<ConsecutivoCompras>();
            this.ConsecutivoDocumentoSoporte = new HashSet<ConsecutivoDocumentoSoporte>();
            this.DetalleCompra = new HashSet<DetalleCompra>();
            this.PagosCompras = new HashSet<PagosCompras>();
            this.R_CompraCliente = new HashSet<R_CompraCliente>();
        }
    
        public int id { get; set; }
        public System.Guid guidCompra { get; set; }
        public System.DateTime fechaCompra { get; set; }
        public string tipoFacturaCompra { get; set; }
        public string prefijoFacturaCompra { get; set; }
        public int number { get; set; }
        public string notes { get; set; }
        public int payment_form_id { get; set; }
        public string namePayment_form { get; set; }
        public int payment_method_id { get; set; }
        public string namePayment_method { get; set; }
        public System.DateTime patment_due_date { get; set; }
        public int estadoCompra { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CargoDescuentoCompra> CargoDescuentoCompra { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConsecutivoCompras> ConsecutivoCompras { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConsecutivoCompras> ConsecutivoCompras1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConsecutivoDocumentoSoporte> ConsecutivoDocumentoSoporte { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleCompra> DetalleCompra { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PagosCompras> PagosCompras { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<R_CompraCliente> R_CompraCliente { get; set; }
    }
}
