//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tokenEmpresa
    {
        public int id { get; set; }
        public System.Guid idEmpresa { get; set; }
        public string token { get; set; }
        public System.DateTime fechaCreacion { get; set; }
    
        public virtual Empresas Empresas { get; set; }
    }
}
