//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Traslados
    {
        public int id { get; set; }
        public System.DateTime fechaTraslado { get; set; }
        public int idusuarioTraslado { get; set; }
        public Nullable<int> idSedeTraslado { get; set; }
        public string tipoTraslado { get; set; }
        public string guidTraslado { get; set; }
        public string descripcionTraslado { get; set; }
        public string sedeEnvio { get; set; }
        public string sedeRecibido { get; set; }
    }
}
