//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Usuario()
        {
            this.Merma = new HashSet<Merma>();
            this.PermisoModulo = new HashSet<PermisoModulo>();
            this.PermisoSubModulo = new HashSet<PermisoSubModulo>();
        }
    
        public int id { get; set; }
        public string identificacionUsuario { get; set; }
        public string nombreUsuario { get; set; }
        public string telefonoUsuario { get; set; }
        public string cuentaUsuario { get; set; }
        public string claveUsuario { get; set; }
        public Nullable<int> idTipoUsuario { get; set; }
        public Nullable<int> idEstadoAI { get; set; }
        public Nullable<System.Guid> guidUsuario { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Merma> Merma { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PermisoModulo> PermisoModulo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PermisoSubModulo> PermisoSubModulo { get; set; }
        public virtual TipoUsuario TipoUsuario { get; set; }
    }
}
