//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_Comandas
    {
        public int id { get; set; }
        public System.DateTime fecha { get; set; }
        public int idServicio { get; set; }
        public int idMesero { get; set; }
        public string nombreMesero { get; set; }
        public string mesas { get; set; }
        public Nullable<int> estado { get; set; }
        public string nombreServicio { get; set; }
    }
}
