//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_Cotizacion
    {
        public int id { get; set; }
        public System.DateTime fechaCotizacion { get; set; }
        public int numeroCotizacion { get; set; }
        public Nullable<decimal> subtotalVenta { get; set; }
        public Nullable<decimal> basesIva { get; set; }
        public Nullable<decimal> ivaVenta { get; set; }
        public Nullable<decimal> totalVenta { get; set; }
        public string fechaVencimiento { get; set; }
        public string observacionVenta { get; set; }
        public int IdSede { get; set; }
        public System.Guid guidCotizacion { get; set; }
        public string nombreCliente { get; set; }
        public string cufe { get; set; }
        public string imagenQR { get; set; }
    }
}
