//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_Compra
    {
        public int id { get; set; }
        public System.Guid guidCompra { get; set; }
        public System.DateTime fechaCompra { get; set; }
        public string tipoFacturaCompra { get; set; }
        public string numeroFactura { get; set; }
        public Nullable<int> idResolucion { get; set; }
        public string prefijo { get; set; }
        public Nullable<int> number { get; set; }
        public string notes { get; set; }
        public int payment_form_id { get; set; }
        public string namePayment_form { get; set; }
        public int payment_method_id { get; set; }
        public string namePayment_method { get; set; }
        public System.DateTime patment_due_date { get; set; }
        public int estadoCompra { get; set; }
        public decimal totalBruto { get; set; }
        public decimal totalDescuento { get; set; }
        public decimal totalBase { get; set; }
        public decimal totalImpuestos { get; set; }
        public decimal totalretefuente { get; set; }
        public Nullable<decimal> impuestosMenosRetenciones { get; set; }
        public Nullable<decimal> totalFactura { get; set; }
        public decimal abonado { get; set; }
        public Nullable<decimal> saldoCompra { get; set; }
        public string nombreProveedor { get; set; }
        public string estado_DS { get; set; }
        public string uuid { get; set; }
        public string numberDS { get; set; }
        public string issue_date { get; set; }
    }
}
