//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_CuentasPC
    {
        public int idClienteCC { get; set; }
        public string documentoClienteCC { get; set; }
        public string nombreClienteCC { get; set; }
        public string telefonoClienteCC { get; set; }
        public string direccionClienteCC { get; set; }
        public decimal TotalCC { get; set; }
        public decimal pagadoCC { get; set; }
        public decimal saldoCC { get; set; }
    }
}
