//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_CuentasVenta
    {
        public int id { get; set; }
        public decimal efectivoVenta { get; set; }
        public int numeroVenta { get; set; }
        public decimal total { get; set; }
        public int idbase { get; set; }
        public int idusuario { get; set; }
        public string numbreUnuario { get; set; }
        public int idvendedor { get; set; }
        public string nombrevendedor { get; set; }
        public int idcliente { get; set; }
        public string nombrecliente { get; set; }
        public int idVehiculo { get; set; }
        public string placa { get; set; }
        public string responsable { get; set; }
        public string telefonoResponsable { get; set; }
        public int idmesa { get; set; }
        public int idZona { get; set; }
        public string nombremesa { get; set; }
    }
}
