//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_CuentaCliente
    {
        public int id { get; set; }
        public System.DateTime fecha { get; set; }
        public int idVenta { get; set; }
        public string nombreCuenta { get; set; }
        public bool preCuenta { get; set; }
        public bool eliminada { get; set; }
        public Nullable<decimal> subtotalVenta { get; set; }
        public Nullable<decimal> ivaVenta { get; set; }
        public Nullable<decimal> totalVenta { get; set; }
        public decimal por_propina { get; set; }
        public Nullable<decimal> propina { get; set; }
        public Nullable<decimal> total_A_Pagar { get; set; }
    }
}
