//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_CuentasServicio
    {
        public int id { get; set; }
        public int idServicio { get; set; }
        public string nombreCuentaServicio { get; set; }
        public Nullable<int> subtotal { get; set; }
        public Nullable<int> impuesto { get; set; }
        public Nullable<int> propina { get; set; }
        public Nullable<int> totalSinPropina { get; set; }
        public Nullable<int> total { get; set; }
        public Nullable<int> estadoCuenta { get; set; }
        public Nullable<int> estadoPreCuenta { get; set; }
    }
}
