//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_DetalleCaja
    {
        public int id { get; set; }
        public Nullable<System.Guid> guidDetalle { get; set; }
        public int idVenta { get; set; }
        public int idPresentacion { get; set; }
        public string codigoProducto { get; set; }
        public string nombreProducto { get; set; }
        public Nullable<int> impuesto_id { get; set; }
        public string presentacion { get; set; }
        public decimal unidad { get; set; }
        public decimal descuentoDetalle { get; set; }
        public Nullable<decimal> preVentaNeto { get; set; }
        public Nullable<decimal> precioVenta { get; set; }
        public Nullable<decimal> porImpuesto { get; set; }
        public Nullable<decimal> baseImpuesto { get; set; }
        public Nullable<decimal> valorImpuesto { get; set; }
        public Nullable<decimal> subTotalDetalleNeto { get; set; }
        public Nullable<decimal> subTotalDetalle { get; set; }
        public Nullable<decimal> totalDetalle { get; set; }
        public Nullable<decimal> costoUnidad { get; set; }
        public Nullable<decimal> contenido { get; set; }
        public Nullable<decimal> costoTotal { get; set; }
        public string observacion { get; set; }
        public string opciones { get; set; }
        public string adiciones { get; set; }
        public int estadoDetalle { get; set; }
        public Nullable<int> idCategoria { get; set; }
        public Nullable<int> idCuentaCliente { get; set; }
        public string nombreCuenta { get; set; }
    }
}
