//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_DetalleComandas
    {
        public int id { get; set; }
        public int idComanda { get; set; }
        public int idDetalleServicio { get; set; }
        public string nombreProducto { get; set; }
        public int cantidad { get; set; }
        public string notas { get; set; }
        public string nombreCuenta { get; set; }
        public int idCategoria { get; set; }
        public string categoria { get; set; }
        public string impresora { get; set; }
        public Nullable<int> estado { get; set; }
    }
}
