//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_DetalleCajaCotizacion
    {
        public int id { get; set; }
        public int idCotizacion { get; set; }
        public string codigoProducto { get; set; }
        public string nombreProducto { get; set; }
        public Nullable<int> idPresentacion { get; set; }
        public decimal cantidadDetalle { get; set; }
        public Nullable<decimal> precioDetalleVentaV { get; set; }
        public Nullable<decimal> precioVenta { get; set; }
        public int descuentoDetalle { get; set; }
        public int recargoDetalle { get; set; }
        public decimal ivaDetalle { get; set; }
        public decimal baseIva { get; set; }
        public Nullable<decimal> valorIva { get; set; }
        public Nullable<decimal> subTotalDetalle { get; set; }
        public Nullable<decimal> totalDetalle { get; set; }
        public string observacion { get; set; }
    }
}
