//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_DetalleTraslado
    {
        public int v_id { get; set; }
        public string v_guidDetalleTraslado { get; set; }
        public string v_guidCorto { get; set; }
        public int v_idProductoTraslado { get; set; }
        public string v_codigoProducto { get; set; }
        public string v_descripcionProducto { get; set; }
        public int v_cantidadproductoTraslado { get; set; }
    }
}
