//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_DetalleCompra
    {
        public int id { get; set; }
        public Nullable<System.Guid> guiDetalleCompra { get; set; }
        public int idCompra { get; set; }
        public int idProducto { get; set; }
        public string code { get; set; }
        public string nombreProducto { get; set; }
        public decimal cantidad { get; set; }
        public decimal contenidoPresentacion { get; set; }
        public Nullable<decimal> cantidadTotal { get; set; }
        public Nullable<decimal> precioUnitario { get; set; }
        public decimal descuento { get; set; }
        public Nullable<decimal> valorDespuesDeDescuento { get; set; }
        public decimal baseImpuesto { get; set; }
        public decimal valorImpuesto { get; set; }
        public decimal valorRetencion { get; set; }
        public Nullable<decimal> totalBruto { get; set; }
        public Nullable<decimal> totalDetalle { get; set; }
        public int estadoDetalle { get; set; }
    }
}
