//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_DetalleServicio
    {
        public int id { get; set; }
        public int idServicio { get; set; }
        public int idPresentacion { get; set; }
        public string nombreProducto { get; set; }
        public Nullable<int> impuesto_id { get; set; }
        public Nullable<decimal> ivaDetalle { get; set; }
        public Nullable<decimal> precioNeto { get; set; }
        public Nullable<decimal> baseImpuesto { get; set; }
        public Nullable<int> precioUnidad { get; set; }
        public Nullable<int> cantidad { get; set; }
        public Nullable<int> total { get; set; }
        public string notas { get; set; }
        public string observacion { get; set; }
        public string estado { get; set; }
        public int idcuenta { get; set; }
        public string nombreCuenta { get; set; }
        public Nullable<int> estadoComanda { get; set; }
        public int idcategoria { get; set; }
        public int estadoDetalle { get; set; }
    }
}
