//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_descuantoDetalleCompra
    {
        public int id { get; set; }
        public System.Guid guidCompra { get; set; }
        public bool descuento { get; set; }
        public string razonDescuento { get; set; }
        public decimal porcentajeDescuento { get; set; }
        public decimal valorDescuento { get; set; }
        public System.Guid guidDetalleCompra { get; set; }
        public Nullable<decimal> baseDescuento { get; set; }
    }
}
