//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_Domicilios
    {
        public System.Guid id { get; set; }
        public System.DateTime fecha { get; set; }
        public int idVenta { get; set; }
        public Nullable<System.Guid> idCliente { get; set; }
        public string celular { get; set; }
        public string cliente { get; set; }
        public string direccion { get; set; }
        public int idEstado { get; set; }
        public string estado { get; set; }
        public string descripcionEstado { get; set; }
    }
}
