//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_InventarioReport
    {
        public int id { get; set; }
        public string codigoProducto { get; set; }
        public string nombreProducto { get; set; }
        public string categoria { get; set; }
        public string presentacion { get; set; }
        public Nullable<decimal> contenido { get; set; }
        public decimal costo_mas_impuesto { get; set; }
        public Nullable<decimal> precio { get; set; }
        public Nullable<decimal> utilidadUnidad { get; set; }
        public Nullable<decimal> inventarioActual { get; set; }
        public Nullable<decimal> costoInventario { get; set; }
        public Nullable<decimal> precioInventario { get; set; }
        public Nullable<decimal> utilidadInventario { get; set; }
    }
}
