//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_Mesas
    {
        public int id { get; set; }
        public Nullable<System.Guid> guidMesa { get; set; }
        public string nombreMesa { get; set; }
        public int idZona { get; set; }
        public string nombreZona { get; set; }
        public int estadoMesa { get; set; }
        public string estadoTexto { get; set; }
    }
}
