//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_PagosCreditoTienda
    {
        public int id_pago_credito_tienda { get; set; }
        public Nullable<System.Guid> guidAbono { get; set; }
        public Nullable<System.DateTime> fecha_pago_credito_tienda { get; set; }
        public Nullable<int> id_cliente_pago_credito_tienda { get; set; }
        public Nullable<decimal> valor_pago_credito_tienda { get; set; }
        public string referenciaDePago { get; set; }
        public Nullable<int> idVentaPago { get; set; }
        public string tipoFactura { get; set; }
        public int numeroVenta { get; set; }
        public Nullable<int> idBaseCaja { get; set; }
        public Nullable<int> idBolsillo { get; set; }
        public string estadoVenta { get; set; }
        public Nullable<decimal> saldoActual { get; set; }
    }
}
