//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_ProductosVentdidos
    {
        public int id { get; set; }
        public System.DateTime fechaVenta { get; set; }
        public string tipoFactura { get; set; }
        public int idProducto { get; set; }
        public Nullable<decimal> cantidadUnidad { get; set; }
        public Nullable<decimal> totalDetalle { get; set; }
        public int idBaseCaja { get; set; }
        public string estadoVenta { get; set; }
        public Nullable<int> idCategoria { get; set; }
    }
}
