//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_Presentacion
    {
        public int id { get; set; }
        public int idTipoPresentacion { get; set; }
        public string nombreTipoPresentacion { get; set; }
        public decimal contenidoPresentacion { get; set; }
        public int estadoPresentacion { get; set; }
        public decimal precioVenta { get; set; }
        public int idProducto { get; set; }
        public System.Guid guidProducto { get; set; }
        public string codigoProducto { get; set; }
        public string nombreProducto { get; set; }
        public string descripcionProducto { get; set; }
        public int idCategoria { get; set; }
        public string nombreCategoria { get; set; }
        public int idTipoMedida { get; set; }
        public string nombreTipoMedida { get; set; }
        public int estadoProducto { get; set; }
        public int gramera { get; set; }
        public decimal porcentaje_impuesto { get; set; }
        public decimal costo_mas_impuesto { get; set; }
        public Nullable<decimal> inventarioInicial { get; set; }
    }
}
