//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_ProductoInsumos
    {
        public int id { get; set; }
        public int idProducto { get; set; }
        public string nombreProducto { get; set; }
        public int idInsumo { get; set; }
        public string nombreInsumo { get; set; }
        public int idUnidadMedida { get; set; }
        public string letraTipoMedida { get; set; }
        public decimal cantidadInsumo { get; set; }
        public string opcional { get; set; }
        public Nullable<decimal> precioInsumo { get; set; }
        public Nullable<int> estado { get; set; }
    }
}
