//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_R_MediosDePago_MediosDePagoInternos
    {
        public int idRMPI { get; set; }
        public int idMedioDePago { get; set; }
        public int idMediosDePagoInternos { get; set; }
        public string nombreRMPI { get; set; }
        public string reporteRDIAN { get; set; }
        public Nullable<int> resporeDian { get; set; }
    }
}
