//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_R_VentaCliente
    {
        public int id { get; set; }
        public string estadoVenta { get; set; }
        public int idCliente { get; set; }
        public string identificationNumber { get; set; }
        public string nameCliente { get; set; }
        public int idVenta { get; set; }
    }
}
