//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_Resoluciones
    {
        public int id { get; set; }
        public string nombreRosolucion { get; set; }
        public string prefijo { get; set; }
        public int idResolucion { get; set; }
        public string numeroResolucion { get; set; }
        public string fechaAvilitacion { get; set; }
        public string vigencia { get; set; }
        public string desde { get; set; }
        public string hasta { get; set; }
        public string caja { get; set; }
        public Nullable<int> consecutivoInicial { get; set; }
        public Nullable<int> consecutivo { get; set; }
        public Nullable<int> estado { get; set; }
        public string estadoText { get; set; }
        public string technical_key { get; set; }
    }
}
