//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_SedesAsignadas
    {
        public int v_idSAsignacion { get; set; }
        public int v_idSedeAsignada { get; set; }
        public int v_idusuarioAsignado { get; set; }
        public string v_nombreusuarioAsignado { get; set; }
        public string v_nombre_empresa { get; set; }
    }
}
