//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_ServicioMesa
    {
        public int id { get; set; }
        public System.DateTime fecha { get; set; }
        public string aliasServicio { get; set; }
        public int idMesero { get; set; }
        public string nombreMesero { get; set; }
        public Nullable<int> estadoServicio { get; set; }
        public Nullable<int> estadoPreCuenta { get; set; }
        public Nullable<decimal> porcentajePropina { get; set; }
        public Nullable<decimal> subtotal { get; set; }
        public Nullable<decimal> impuesto { get; set; }
        public Nullable<decimal> totalsinservicio { get; set; }
        public Nullable<decimal> servicio { get; set; }
        public Nullable<decimal> totalconservicio { get; set; }
    }
}
