//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_SeguimientoDomicilio
    {
        public int id { get; set; }
        public System.Guid idDomicilio { get; set; }
        public System.DateTime fechaSeguimiento { get; set; }
        public int idEstado { get; set; }
        public string estado { get; set; }
        public string Observacion { get; set; }
    }
}
