//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_TablaVentas
    {
        public int id { get; set; }
        public System.DateTime fechaVenta { get; set; }
        public string tipoFactura { get; set; }
        public string prefijo { get; set; }
        public int numeroVenta { get; set; }
        public int descuentoVenta { get; set; }
        public Nullable<int> idMedioDePago { get; set; }
        public Nullable<int> idResolucion { get; set; }
        public Nullable<int> idFormaDePago { get; set; }
        public Nullable<decimal> subtotalVenta { get; set; }
        public Nullable<decimal> basesIva { get; set; }
        public decimal basesIva_5 { get; set; }
        public decimal basesIva_19 { get; set; }
        public decimal IVA { get; set; }
        public decimal IVA_5 { get; set; }
        public decimal IVA_19 { get; set; }
        public decimal INC { get; set; }
        public decimal INCBolsas { get; set; }
        public decimal otrosImpuestos { get; set; }
        public decimal ivaVenta { get; set; }
        public decimal totalVenta { get; set; }
        public decimal total_A_Pagar { get; set; }
        public Nullable<decimal> efectivoVenta { get; set; }
        public Nullable<decimal> cambioVenta { get; set; }
        public string formaDePago { get; set; }
        public Nullable<decimal> abonoEfectivo { get; set; }
        public Nullable<decimal> abonoTarjeta { get; set; }
        public Nullable<decimal> totalPagadoVenta { get; set; }
        public Nullable<decimal> totalPendienteVenta { get; set; }
        public string estadoVenta { get; set; }
        public string medioDePago { get; set; }
        public string numeroReferenciaPago { get; set; }
        public Nullable<int> diasCredito { get; set; }
        public Nullable<System.DateTime> fechaVencimiento { get; set; }
        public string observacionVenta { get; set; }
        public int IdSede { get; set; }
        public System.Guid guidVenta { get; set; }
        public Nullable<decimal> costoTotalVenta { get; set; }
        public Nullable<decimal> utilidadTotalVenta { get; set; }
        public int idCliente { get; set; }
        public string nit { get; set; }
        public string nombreCliente { get; set; }
        public Nullable<decimal> propina { get; set; }
        public string cufe { get; set; }
        public string estadoFE { get; set; }
        public string imagenQR { get; set; }
        public Nullable<int> idBaseCaja { get; set; }
        public string razonDescuento { get; set; }
        public Nullable<decimal> por_propina { get; set; }
    }
}
