//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_Traslados
    {
        public int v_idTraslado { get; set; }
        public string v_guidTraslado { get; set; }
        public System.DateTime v_fechaTraslado { get; set; }
        public int v_idusuarioTraslado { get; set; }
        public string v_NombreusuarioTraslado { get; set; }
        public Nullable<int> v_idSedeTraslado { get; set; }
        public string v_tipoTraslado { get; set; }
        public string v_descripcionTraslado { get; set; }
        public string v_SedeEnvio { get; set; }
        public string v_SedeRecibido { get; set; }
    }
}
