//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_TurnosCaja
    {
        public int id { get; set; }
        public Nullable<System.DateTime> fechaApertura { get; set; }
        public Nullable<System.DateTime> fechaCierre { get; set; }
        public Nullable<int> idUsuarioApertura { get; set; }
        public string nombreUsuario { get; set; }
        public Nullable<decimal> valorBase { get; set; }
        public Nullable<decimal> ventasCredito { get; set; }
        public Nullable<decimal> totalEfectivo { get; set; }
        public Nullable<decimal> efectivoMasBase { get; set; }
        public Nullable<decimal> pagoCC_Efectivo { get; set; }
        public Nullable<decimal> pagoCC_Targeta { get; set; }
        public Nullable<decimal> pagoCP_Efectivo { get; set; }
        public Nullable<decimal> gastos_Efectivo { get; set; }
        public Nullable<decimal> ventasEfectivo { get; set; }
        public Nullable<decimal> ventasTargeta { get; set; }
        public Nullable<decimal> totalIngresos { get; set; }
        public Nullable<decimal> totalEgresos { get; set; }
        public Nullable<decimal> producido { get; set; }
        public string estadoBase { get; set; }
    }
}
