//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_VentasPagosInternos
    {
        public int id { get; set; }
        public System.DateTime fechaVenta { get; set; }
        public string tipoFactura { get; set; }
        public string medioDePago { get; set; }
        public Nullable<int> idBaseCaja { get; set; }
        public string numeroReferenciaPago { get; set; }
        public int idMedioDePagointerno { get; set; }
        public string medioPagoInterno { get; set; }
        public decimal valorPago { get; set; }
    }
}
