//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_VentasPorCategoria
    {
        public int idVentaCategoria { get; set; }
        public System.DateTime fechaVenta { get; set; }
        public string tipoFactura { get; set; }
        public int idCategoria { get; set; }
        public string nombreCategoria { get; set; }
        public string nombreProducto { get; set; }
        public Nullable<decimal> precio { get; set; }
        public Nullable<decimal> unidad { get; set; }
        public Nullable<decimal> total { get; set; }
    }
}
