//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_Vendedor
    {
        public int id { get; set; }
        public string nombreVendedor { get; set; }
        public string telefonoVendedor { get; set; }
        public string calveVendedor { get; set; }
        public Nullable<int> cajaMovil { get; set; }
        public string cajaWeb { get; set; }
    }
}
