//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_VentaInsumo
    {
        public System.DateTime fechaVenta { get; set; }
        public int idInsumo { get; set; }
        public string nombreProducto { get; set; }
        public decimal cantidadInsumo { get; set; }
        public Nullable<decimal> multiplicado { get; set; }
        public Nullable<decimal> descontado { get; set; }
    }
}
