//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VentaActiva
    {
        public int id { get; set; }
        public Nullable<int> idCajeroVentaActiva { get; set; }
        public Nullable<int> numeroVentaActiva { get; set; }
        public string tipoPagoVentaActiva { get; set; }
        public string tipoFacturaVentaActiva { get; set; }
        public Nullable<int> subTotalVentaActiva { get; set; }
    }
}
