//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VistaMediosDePago
    {
        public int id { get; set; }
        public int idBediosDePagoDIAN { get; set; }
        public string nombreMedioDePagoDIAN { get; set; }
        public int idMedioDePagoInterno { get; set; }
        public string nombreMedioDePagoInterno { get; set; }
        public Nullable<int> resporeDian { get; set; }
    }
}
